[package]
name = "compio-quic"
version = "0.1.0"
description = "QUIC for compio"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "net", "quic"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# Workspace dependencies
compio-io = { workspace = true }
compio-buf = { workspace = true }
compio-log = { workspace = true }
compio-net = { workspace = true }
compio-runtime = { workspace = true, features = ["time"] }

quinn-proto = "0.11.3"
rustls = { workspace = true, features = ["ring"] }
rustls-platform-verifier = { version = "0.3.3", optional = true }
rustls-native-certs = { version = "0.7.1", optional = true }
webpki-roots = { version = "0.26.3", optional = true }

# Utils
bytes = "1.7.1"
event-listener = "5.3.1"
flume = { workspace = true }
futures-util = { workspace = true }
thiserror = "1.0.63"

# Windows specific dependencies
[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Networking_WinSock"] }

# Linux specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
compio-driver = { workspace = true }
compio-macros = { workspace = true }
rcgen = "0.13.1"
socket2 = { workspace = true, features = ["all"] }
tracing-subscriber = "0.3.18"

[features]
default = ["webpki-roots"]
futures-io = ["futures-util/io"]
platform-verifier = ["dep:rustls-platform-verifier"]
native-certs = ["dep:rustls-native-certs"]
webpki-roots = ["dep:webpki-roots"]
