[package]
name = "compio"
version = "0.2.1"
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com"]
readme = "README.md"
license = "MIT"
description = "completion based async runtime"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "fs", "net", "iocp", "io-uring"]
repository = "https://github.com/Berrysoft/compio"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]

[dependencies]
async-task = "4"
bytes = { version = "1", optional = true }
cfg-if = "1"
futures-util = "0.3"
once_cell = "1"
slab = "0.4"
socket2 = { version = "0.5", features = ["all"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
futures-channel = "0.3"
tempfile = "3"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "rt"] }

[target.'cfg(target_os = "windows")'.dependencies]
crossbeam-queue = "0.3"
widestring = "1"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }

[target.'cfg(target_os = "windows")'.dev-dependencies]
windows-sys = { version = "0.48", features = ["Win32_Security_Authorization"] }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.6"
libc = "0.2"

[features]
default = ["runtime"]
runtime = []
signal = ["runtime"]
time = ["runtime"]
all = ["time", "signal"]

read_buf = []
nightly = ["read_buf"]

[[example]]
name = "tick"
required-features = ["time", "signal"]

[[bench]]
name = "fs"
harness = false

[[bench]]
name = "net"
harness = false

[[bench]]
name = "named_pipe"
harness = false
