[workspace]
members = ["compio", "compio-buf", "compio-driver", "compio-macros"]
resolver = "2"

[workspace.dependencies]
compio-buf = { path = "./compio-buf" }
compio-macros = { path = "./compio-macros" }
