[package]
name = "compio"
version = "0.1.0"
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com"]
readme = "README.md"
license = "MIT"
description = "completion based async runtime"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "fs", "iocp", "io-uring"]
repository = "https://github.com/Berrysoft/compio"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]

[dependencies]
async-task = "4"
bytes = { version = "1", optional = true }
cfg-if = "1"
futures-util = "0.3"
once_cell = "1"
slab = "0.4"
socket2 = "0.5"

[dev-dependencies]
tempfile = "3"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_Threading",
] }
aligned-array = "1"
widestring = "1"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.6"

[features]
default = []
runtime = []
read_buf = []
nightly = ["read_buf"]

[[example]]
name = "basic"
required-features = ["runtime"]

[[example]]
name = "net"
required-features = ["runtime"]

[[test]]
name = "driver"
required-features = ["runtime"]

[[test]]
name = "file"
required-features = ["runtime"]
