[package]
name = "compio-net"
version = "0.1.0"
description = "Networking IO for compio"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "net"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg docsrs"]

[dependencies]
# Workspace dependencies
compio-buf = { workspace = true }
compio-driver = { workspace = true }
compio-io = { workspace = true, optional = true }
compio-runtime = { workspace = true, optional = true }

cfg-if = "1"
either = "1"
socket2 = { version = "0.5", features = ["all"] }

[target.'cfg(windows)'.dependencies]
widestring = "1"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_System_IO",
] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

# Shared dev dependencies for all platforms
[dev-dependencies]
futures-util = "0.3"
tempfile = "3"

[features]
runtime = ["dep:compio-io", "dep:compio-runtime"]
