[package]
name = "compio-http"
version = "0.1.0"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "net"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
compio-buf = { workspace = true }
compio-io = { workspace = true }
compio-runtime = { workspace = true }
compio-net = { workspace = true, features = ["runtime"] }
compio-tls = { workspace = true }

native-tls = { version = "0.2", optional = true }

hyper = { version = "0.14", features = ["client", "http1"] }
send_wrapper = { version = "0.6", features = ["futures"] }
tokio = { version = "1", default-features = false }

[dev-dependencies]
compio-macros = { workspace = true }

[features]
default = ["native-tls"]
native-tls = ["compio-tls/native-tls", "dep:native-tls"]
vendored = ["native-tls?/vendored"]
