[package]
name = "compio-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
compio-buf = { workspace = true, optional = true }
compio-driver = { workspace = true }
compio-runtime = { workspace = true, optional = true }

# Windows specific dependencies
[target.'cfg(target_os = "windows")'.dependencies]
widestring = "1"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_System_SystemServices",
] }

# Windows specific dev dependencies
[target.'cfg(target_os = "windows")'.dev-dependencies]
windows-sys = { version = "0.48", features = ["Win32_Security_Authorization"] }

# Unix specific dependencies
[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
runtime = ["dep:compio-buf", "dep:compio-runtime"]

# Nightly features
allocator_api = []
nightly = ["allocator_api", "compio-buf?/allocator_api"]
