[package]
name = "compio"
version = "0.7.0"
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
description = "completion based async runtime"
categories = ["asynchronous", "filesystem", "network-programming"]
keywords = ["async", "fs", "iocp", "io-uring", "net"]
repository = "https://github.com/Berrysoft/compio"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-ios",
    "aarch64-linux-android",
    "x86_64-unknown-dragonfly",
    "x86_64-unknown-freebsd",
    "x86_64-unknown-illumos",
    "x86_64-unknown-netbsd",
    "x86_64-unknown-openbsd",
]

# Shared dependencies for all platforms
[dependencies]
# Workspace dependencies
compio-buf = { workspace = true }

# Utils
cfg-if = "1"
once_cell = "1" # may be excluded from linking if the unstable equivalent is used
slab = "0.4"
socket2 = { version = ">=0.5.4", features = ["all"] }

# Runtime dependencies for all platforms
smallvec = { version = "1", optional = true }
async-task = { version = "4", optional = true }
futures-util = { version = "0.3", optional = true }

# Shared dev dependencies for all platforms
[dev-dependencies]
bumpalo = "3"
criterion = { version = "0.5", features = ["async_tokio"] }
futures-channel = "0.3"
compio-buf = { workspace = true, features = ["arrayvec"] }
arrayvec = "0.7"
tempfile = "3"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "rt"] }

# Windows specific dependencies
[target.'cfg(target_os = "windows")'.dependencies]
compio-buf = { workspace = true, features = ["arrayvec"] }
widestring = "1"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }

# Windows specific dev dependencies
[target.'cfg(target_os = "windows")'.dev-dependencies]
windows-sys = { version = "0.48", features = ["Win32_Security_Authorization"] }

# Linux specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { version = "0.6", optional = true }
polling = { version = "3", optional = true }
libc = "0.2"

# Other platform dependencies
[target.'cfg(all(not(target_os = "linux"), unix))'.dependencies]
polling = "3"
libc = "0.2"

[features]
default = ["runtime", "io-uring"]
io-uring = ["dep:io-uring"]
runtime = ["dep:async-task", "dep:futures-util", "dep:smallvec"]
event = ["runtime", "compio-buf/arrayvec"]
signal = ["event"]
time = ["runtime"]
all = ["time", "signal"]

# Nightly features
allocator_api = ["bumpalo/allocator_api", "compio-buf/allocator_api"]
lazy_cell = []
once_cell_try = []
read_buf = ["compio-buf/read_buf"]
nightly = ["allocator_api", "lazy_cell", "once_cell_try", "read_buf"]

[[example]]
name = "tick"
required-features = ["time", "signal"]

[[bench]]
name = "fs"
harness = false

[[bench]]
name = "net"
harness = false

[[bench]]
name = "named_pipe"
harness = false

[[test]]
name = "event"
required-features = ["event"]
