[package]
name = "compio"
version = "0.8.0"
description = "completion based async runtime"
categories = ["asynchronous", "filesystem", "network-programming"]
keywords = ["async", "fs", "iocp", "io-uring", "net"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
rustdoc-args = ["--cfg docsrs"]
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-ios",
    "aarch64-linux-android",
    "x86_64-unknown-dragonfly",
    "x86_64-unknown-freebsd",
    "x86_64-unknown-illumos",
    "x86_64-unknown-netbsd",
    "x86_64-unknown-openbsd",
]

# Shared dependencies for all platforms
[dependencies]
# Workspace dependencies
compio-buf = { workspace = true }
compio-driver = { workspace = true }
compio-runtime = { workspace = true, optional = true }
compio-macros = { workspace = true, optional = true }
compio-fs = { workspace = true }
compio-io = { workspace = true }
compio-net = { workspace = true }
compio-signal = { workspace = true, optional = true }
compio-dispatcher = { workspace = true, optional = true }

# Shared dev dependencies for all platforms
[dev-dependencies]
compio-buf = { workspace = true, features = ["arrayvec"] }
compio-macros = { workspace = true }

bumpalo = "3"
criterion = { version = "0.5", features = ["async_tokio"] }
futures-util = "0.3"
futures-channel = "0.3"
tempfile = "3"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "rt"] }

[features]
default = ["runtime", "io-uring"]
io-uring = ["compio-driver/io-uring"]
polling = ["compio-driver/polling"]
runtime = ["dep:compio-runtime", "compio-fs/runtime", "compio-net/runtime"]
macros = ["dep:compio-macros", "runtime"]
event = ["compio-runtime/event", "runtime"]
signal = ["dep:compio-signal", "event"]
time = ["compio-runtime/time", "runtime"]
dispatcher = ["dep:compio-dispatcher", "runtime"]
all = ["time", "macros", "signal", "dispatcher"]

# Nightly features
allocator_api = [
    "bumpalo/allocator_api",
    "compio-buf/allocator_api",
    "compio-io/allocator_api",
]
lazy_cell = ["compio-signal?/lazy_cell"]
once_cell_try = [
    "compio-driver/once_cell_try",
    "compio-runtime?/once_cell_try",
    "compio-signal?/once_cell_try",
]
read_buf = ["compio-buf/read_buf"]
try_trait_v2 = ["compio-buf/try_trait_v2"]
nightly = [
    "allocator_api",
    "lazy_cell",
    "once_cell_try",
    "read_buf",
    "try_trait_v2",
]


[[example]]
name = "basic"
required-features = ["macros"]

[[example]]
name = "named_pipe"
required-features = ["macros"]

[[example]]
name = "net"
required-features = ["macros"]

[[example]]
name = "unix"
required-features = ["macros"]

[[example]]
name = "tick"
required-features = ["time", "signal", "macros"]

[[example]]
name = "dispatcher"
required-features = ["macros", "dispatcher"]

[[bench]]
name = "fs"
harness = false

[[bench]]
name = "net"
harness = false

[[bench]]
name = "named_pipe"
harness = false

[[test]]
name = "event"
required-features = ["event"]

[[test]]
name = "dispatcher"
required-features = ["dispatcher"]
