[package]
name = "compio-tls"
version = "0.1.0"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "net", "tls"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
compio-buf = { workspace = true }
compio-io = { workspace = true }

native-tls = { version = "0.2.11", optional = true }
rustls = { version = "0.21.8", optional = true }

[dev-dependencies]
compio-net = { workspace = true }
compio-runtime = { workspace = true }

rustls-native-certs = "0.6.3"

[features]
default = ["native-tls"]
