[package]
name = "compio-io"
version = "0.1.0"
categories = ["asynchronous"]
keywords = ["async", "io"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
compio-buf = { workspace = true, features = ["arrayvec"] }
paste = { workspace = true }

[dev-dependencies]
# use tokio to show this crate doesn't depend on the compio runtime
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
# Nightly features
allocator_api = []
nightly = ["allocator_api", "compio-buf/allocator_api"]
