[package]
name = "compio-io"
version = "0.1.0"
categories = ["asynchronous"]
keywords = ["async", "io"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
compio-buf = { workspace = true, features = ["arrayvec"] }
paste = { workspace = true }

[dev-dependencies]
compio-runtime = { workspace = true }
# use tokio to show this crate doesn't depend on the compio runtime
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = []
compat = []

# Nightly features
allocator_api = ["compio-buf/allocator_api"]
read_buf = ["compio-buf/read_buf"]
nightly = ["allocator_api", "read_buf"]
