[package]
name = "compio-log"
version = "0.1.0"
description = "log of compio"
categories = ["asynchronous"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
enable-log = []
